apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-ops-config
data:
  cluster-id: change-me-cluster-id
  filebeat.yml: |
    filebeat.config.inputs:
      enabled: true
      path: inputs.d/*.yml
      reload.enabled: true
      reload.period: 10s
    output.console:
      pretty: true
