apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: filebeat-ops-server
    newName: filebeat-ops-server
    newTag: local
  - name: filebeat-ops-sidecar
    newName: filebeat-ops-sidecar
    newTag: local
