apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base
images:
  - name: filebeat-ops-server
    newName: hub.kce.ksyun.com/ked-monitoring/filebeat-ops-server
    newTag: "8d2dae9"
  - name: filebeat-ops-sidecar
    newName: hub.kce.ksyun.com/ked-monitoring/filebeat-ops-sidecar
    newTag: "8d2dae9"
